### ISSUE TITLE
Running command with no arguments should return usage

### ISSUE THREAD

**Issue by rikkuness** [queicherius/abc-environment#15]
Just for us newbies :)

Currently returns:
```
# abc
👎  Command `undefined` does not exist
```

If I remember I'll PR you.

**Comment by rikkuness** [comment]
#16 fixes

**Comment by queicherius** [comment]
Sweet, thanks! ❤️ I'll release a new version.

**Comment by queicherius** [comment]
Released in `v1.3.0` (42e485c85e947b1f4b343be914487b217cae5fbf)
